### ISSUE TITLE
More responsive web design required

### ISSUE THREAD

**Issue by soc** [soc/scala-lang#20]
While there was some effort improving things, we are clearly not where we want to be yet.

If you find any responsiveness issues, please leave a comment/screenshot!

**Comment by soc** [comment]
[] The website headers are not responsive.

**Comment by jlprat** [comment]
For example when the screen is only 550 px wide you get the following problems (on top of the headers)
- [ ] What's new section is not responsive
- [ ] Recently section is not responsive
- [ ] Footer links go off the background color
- [ ] Footer copyright's Scala logo leaves too much spacing

**Comment by soc** [comment]
Thanks!

**Comment by DavidPrichard** [comment]
I'm looking into this after seeing the issue mentioned on /r/scala.

Screenshots are helpful, but please include the page's URL, and the OS / browser you were using so I can reproduce the issue myself.

**Comment by soc** [comment]
@DavidPrichard Screenshots are a good idea! We should do that.

I "fixed" the issue of "Documentation pages fail to reflow text" by disabling the `<meta>` tag that did this everywhere except for the frontpage. Not pretty but at least text is now readable: https://github.com/soc/scala-lang/commit/d33765aa804cd90713f602c0ae2a7b0ab799881d#diff-84234bcd3917743b8d1f73948b31f378R10

**Comment by DavidPrichard** [comment]
@soc Well, the screenshots were your idea, per the top comment. :)

I didn't realize the meta tag was disabled; I was wondering why I couldn't reproduce the issues above. Shoulda checked back here.

Anyway, I'm still working on this. Nothing seems too perverse in the HTML and CSS; should have a PR next week. The text reflowing seems to be due to some styles in `boostrap.css` that give several items a fixed `width`, preventing the page from becoming any narrower. Some funkiness is caused by `margin: auto` on several elements, which shrinks to nothing when the page is sufficiently narrow, leaving them uncomfortably close to each other and the edge of the page.
